# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeyweekCli < Formula
  desc "Heyweek CLI"
  homepage "https://heyweek.com"
  version "1.7.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/heyweek/homebrew-heyweek-cli/releases/download/v1.7.0/Heyweek_v1.7.0_macOS_amd64.zip", using: CurlDownloadStrategy
    sha256 "3ae1f8f726beb4a45e5510c80726e55a102c1835f49df423a7a46d4195327d78"

    def install
      bin.install "bin/hw"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/heyweek/homebrew-heyweek-cli/releases/download/v1.7.0/Heyweek_v1.7.0_macOS_arm64.zip", using: CurlDownloadStrategy
    sha256 "b19a9180e423239d6b17b351d03688014d17fd671fc49cc3332d2c07dbd7c452"

    def install
      bin.install "hw"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Heyweek CLI! To get started run `hw auth login` first.
    EOS
  end
end
