# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeyweekCli < Formula
  desc "Heyweek CLI"
  homepage "https://heyweek.com"
  version "1.11.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/heyweek/homebrew-heyweek-cli/releases/download/v1.11.1/Heyweek_v1.11.1_macOS_amd64.zip", using: CurlDownloadStrategy
    sha256 "f1e330d7fabb1046e84167b0af344169f431009476ce5cdd5f82a37e3561d044"

    define_method(:install) do
      bin.install "hw"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/heyweek/homebrew-heyweek-cli/releases/download/v1.11.1/Heyweek_v1.11.1_macOS_arm64.zip", using: CurlDownloadStrategy
    sha256 "77f6408bbd1c1fc4b403c8bea0e92bcae56548c4e5f02d8c575cd3360dc81775"

    define_method(:install) do
      bin.install "hw"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Heyweek CLI! To get started run `hw auth login` first.
    EOS
  end
end
