# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeyweekCli < Formula
  desc "Heyweek CLI"
  homepage "https://heyweek.com"
  version "1.7.1"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/heyweek/homebrew-heyweek-cli/releases/download/v1.7.1/Heyweek_v1.7.1_macOS_amd64.zip", using: CurlDownloadStrategy
    sha256 "0df4f960f5c18f67c09d413b76dbb4a690298ee25b9bb61ca6e552e1176a94c5"

    def install
      bin.install "bin/hw"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/heyweek/homebrew-heyweek-cli/releases/download/v1.7.1/Heyweek_v1.7.1_macOS_arm64.zip", using: CurlDownloadStrategy
    sha256 "5a511e59c4e7f07ab5019381b1fecc2d679ff06e49484580268b483c6a7387e7"

    def install
      bin.install "hw"
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Heyweek CLI! To get started run `hw auth login` first.
    EOS
  end
end
