# This file was generated by GoReleaser. DO NOT EDIT.
cask "heyweek-cli" do
  name "heyweek-cli"
  desc "Heyweek CLI"
  homepage "https://heyweek.com"
  version "1.8.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heyweek-cli"

  on_macos do
    on_intel do
      url "https://github.com/heyweek/homebrew-heyweek-cli/releases/download/v#{version}/Heyweek_v#{version}_macOS_amd64.zip",
        using: :homebrew_curl
      sha256 "2b6a90797d5c2f3909943f81cdcf3cc2bc2cad08361a9fa2759c1e29715a005b"
    end
    on_arm do
      url "https://github.com/heyweek/homebrew-heyweek-cli/releases/download/v#{version}/Heyweek_v#{version}_macOS_arm64.zip",
        using: :homebrew_curl
      sha256 "a17d91a38ccaf244239251c00128ccb20661ca4a55334f77e61e5fdd7a43bda1"
    end
  end

  caveats do
    "❤ Thanks for installing the Heyweek CLI! To get started run `hw auth login` first."
  end

  # No zap stanza required
end
